defmodule ExYarnTest do
  use ExUnit.Case, async: true

  doctest ExYarn

  test "parses comments correctly" do
    input = """
    # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
    # yarn lockfile v1

    "foo":
      bar foo
    """

    expected_result = {
      %{"foo" => %{"bar" => "foo"}},
      [" THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.", " yarn lockfile v1"]
    }

    {:ok, result} = ExYarn.parse(input)

    assert expected_result == result
  end

  test "parses booleans correctly" do
    input = """
    foo:
      bar true
      foo false
    """

    expected_result = %{"foo" => %{"bar" => true, "foo" => false}}

    {:ok, {result, _}} = ExYarn.parse(input)
    assert expected_result == result
  end

  test "parses integers correctly" do
    input = """
    foo:
      bar 10
    """

    expected_result = %{"foo" => %{"bar" => 10}}

    {:ok, {result, _}} = ExYarn.parse(input)
    assert expected_result == result
  end
end
