name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: elixir:1.10.4-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache plts
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}', github.workspace)) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install hex
        run: mix local.hex --force

      - name: Install rebar
        run: mix local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Test
        env:
          MIX_ENV: test
        run: mix test
      
      - name: Format
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict

      - name: Dialyzer
        run: mix dialyzer 
